### ISSUE TITLE
flatten-vs-shade incompatibility

### ISSUE THREAD

**Issue by mkarg** [mojohaus/flatten-maven-plugin#100]
When using Flatten Maven Plugin in the same project with Maven Shade Plugin then the dependency reduced POM is *not* flattened.

One of both plugins must have a bug, but which one?

I noticed that the cause seems to be this line of the shade plugin:
[`Model model = project.getOriginalModel();`](https://github.com/apache/maven-shade-plugin/blob/e1f181f9ef9f196f299abe4cceeb1caeefcf4cdc/src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java#L931)
For test purposes I changed it to `project.getModel()` which fixes the problem (i. e. it now reduces the *flattened* POM), but imposes a new problem: This does not flatten the POM, it flattens the *effective* POM.

Any ideas appreciated, so I could track the *original* cause, and file the bug in the *right* tracker.

**Comment by ribasco** [comment]
I encountered  the exact issue you described. I was able to fix this by simply changing the order of execution between shade and flatten. Just make sure `flatten` comes after `shade`. (See answer on [StackOverflow](https://stackoverflow.com/questions/52552329/use-maven-flatten-plugin-and-maven-shade-plugin-at-the-same-time))

**Comment by mohanraj-r** [comment]
👍 Also had to change the `phase` to `package` for it to work

> I encountered the exact issue you described. I was able to fix this by simply changing the order of execution between shade and flatten. Just make sure `flatten` comes after `shade`. (See answer on [StackOverflow](https://stackoverflow.com/questions/52552329/use-maven-flatten-plugin-and-maven-shade-plugin-at-the-same-time))

**Comment by mkarg** [comment]
@olamy @khmarbaise Can you please comment your ideas on this issue? How shall we go on?

**Comment by bjacquemoud** [comment]
I encountered the exact issue you described. 
I was able to fix this only by simply setting createDependencyReducedPom to false

Changing the order of execution between shade and flatten didn't work for me

The reduced pom is indeed not flattened but also I have noticed that there is a error with the generated reduced pom with  the parents's relativePath 

originally its 	<relativePath>../weasis-parent/pom.xml</relativePath>
and it becomes 	<relativePath>../../weasis-parent/pom.xml</relativePath> when reduced 

@see https://i.stack.imgur.com/boolA.png  

that's probably the reason why it cannot resolve the parents pom 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade (default) on project weasis-launcher: Error creating shaded jar: 1 problem was encountered while building the effective model for org.weasis.launcher:weasis-launcher:[unknown-version]
[ERROR] [FATAL] Non-resolvable parent POM for org.weasis.launcher:weasis-launcher:[unknown-version]: Could not transfer artifact org.weasis:weasis-parent:pom:${revision}${changelist} from/to hug-nexus-repo-proxy (http://..../repository/maven-public): Failed to transfer file: http://..../repository/maven-public/org/weasis/weasis-parent/$%7Brevision%7D$%7Bchangelist%7D/weasis-parent-$%7Brevision%7D$%7Bchangelist%7D.pom. Return code is: 400 , ReasonPhrase:Invalid repository path. and 'parent.relativePath' points at wrong local POM @ line 3, column 11
[ERROR]  for project org.weasis.launcher:weasis-launcher:[unknown-version] at ....
```

**Comment by mkarg** [comment]
@olamy @khmarbaise Can you **please** comment your ideas on this issue? **How shall we go on?**

**Comment by raydac** [comment]
@mkarg 
I also get problems in work with flatten+shade, so that use [uber-pom](https://github.com/raydac/uber-pom/blob/master/README.md) plugin to merge project tree

**Comment by alamar** [comment]
> Just make sure flatten comes after shade.

While there may be uses for that, shade will not reduce dependencies coming from parent POM in this case.

**Comment by gzm55** [comment]
> When using Flatten Maven Plugin in the same project with Maven Shade Plugin then the dependency reduced POM is _not_ flattened.
> 
> One of both plugins must have a bug, but which one?
> 
> I noticed that the cause seems to be this line of the shade plugin: [`Model model = project.getOriginalModel();`](https://github.com/apache/maven-shade-plugin/blob/e1f181f9ef9f196f299abe4cceeb1caeefcf4cdc/src/main/java/org/apache/maven/plugins/shade/mojo/ShadeMojo.java#L931) For test purposes I changed it to `project.getModel()` which fixes the problem (i. e. it now reduces the _flattened_ POM), but imposes a new problem: This does not flatten the POM, it flattens the _effective_ POM.
> 
> Any ideas appreciated, so I could track the _original_ cause, and file the bug in the _right_ tracker.

Hi @mkarg , changing to `project.getModel()` will break MSHADE-185.

The root cause should be the *inconsistent* of `project.getOriginalModel()` and `readModel(project.getFile())`. So every plugin switching the pom file *should* also update original model to reflect the new pom file content. And flatten and shade plugins share the same problem.

The work around of run flatten in `package` phase does not work when enable `useDependencyReducedPomInJar` in the shade plugin, i.e., the pom in the shaded jar is not processed by the flatten plugin.

**Comment by wangliang181230** [comment]
I think `flatten` only needs to ensure that the POM generated by the `shade` is correct and available.

**Comment by yeroc** [comment]
Any chance the above PR will get reviewed?  Assuming it does indeed fix the issue.  I just got bitten by this but can't find a work around since I need to create a dependency-reduced pom at the same time.

**Comment by gzm55** [comment]
> Any chance the above PR will get reviewed? Assuming it does indeed fix the issue. I just got bitten by this but can't find a work around since I need to create a dependency-reduced pom at the same time.

either of these two pr would fix tie incompatibility issue:

#281 
apache/maven-shade-plugin#129
