### ISSUE TITLE
Running with latest maven version

### ISSUE THREAD

**Issue by Nitwel** [mojohaus/flatten-maven-plugin#107]
Sorry if this question is a bit stupid but is it possible to run this plugin with Maven 4.0.0 and if so, how?
Thanks. 😄

**Comment by lasselindqvist** [comment]
The newest Maven version is 3.6.2, so Maven 4.0.0 doesn't exist yet.

**Comment by Nitwel** [comment]
I'm getting this error and I'm using the latest maven version. So does this plugin work for the latest version? If not, whats the latest version, that works with this plugin? Thanks for the help.
```
[ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.1.0:flatten (flatten) on project ProjectX: The plugin org.codehaus.mojo:flatten-maven-plugin:1.1.0 requires Maven version 3.2.5 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException
```

**Comment by lasselindqvist** [comment]
You can check your Maven version with "mvn --version". According to that log, you are not using the latest 3.6.2. See https://maven.apache.org/install.html for installation instructions and make sure the right version is in your PATH variable.

**Comment by Nitwel** [comment]
Well, thats what maven says:
![grafik](https://user-images.githubusercontent.com/22577866/65377483-ecfd0000-dcac-11e9-9b8f-17a135e85541.png)

Also, I'm using docker with the latest maven image so Idk. 😕

**Comment by lasselindqvist** [comment]
One possibility is that you are building a project, which has maven-wrapper (https://github.com/takari/maven-wrapper) in use, and running mvnw then uses whatever Maven version that wrapper is defined to use. Other than that, it is difficult to say without seeing the project.

**Comment by Nitwel** [comment]
Ah ok, got it. There was another image used in this specific job and therefore the maven version was up to date in the first job but not in the second. Thanks for the help and have a nice evening. 😄 👍
