### ISSUE TITLE
Upgrade maven-artifact-transfer

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/flatten-maven-plugin#109]
Upgrade to http://maven.apache.org/shared/maven-artifact-transfer/ 0.11.0

**Comment by khmarbaise** [comment]
Need to find out why the CreateEffectivePomTest accesses internal classes of the artifact-transfer and what the purpose of the test is...?

**Comment by famod** [comment]
@khmarbaise Is this a blocker for a 1.2.0 release? Would be nice to finally see such a 1.2.0 release after almost one year...

**Comment by rfscholte** [comment]
@famod I'd like to add PR #1. The solution is not good enough but we're close, working on that.

**Comment by hohwille** [comment]
I am involved in way too many OSS projects. Will post a thread about the maintainership of this plugin on the dev group.
However, if after a year nothing happened, I clicked on the pencil icon to replace `0.8.0` with `0.11.0` in the browser and clicked two buttons to create PR for it: #113
Travis showed that there have been incompatible changes in maven-articact-transfer. So a pom change is not enough. No time for a refactoring right now.
BTW: I can do a release `1.2.0` and move all open `1.2.0` issues to a new `1.3.0` milestone if that is of some help...

**Comment by slachiewicz** [comment]
done in c5032e4e27a9e9bbc7e93543fe36d85b436e10e0
