### ISSUE TITLE
New flattenmode 'flat'

### ISSUE THREAD

**Issue by alexsuter** [mojohaus/flatten-maven-plugin#112]
I'm asking for a new flattenmode e.g. 'flat'. I want exactly the same as for 'resolveCiFriendliesOnly', but pressed flat, i.e. the resolution of all parent poms. So I don't have to deploy parent poms.

**Comment by hohwille** [comment]
By default this is exactly what `flatten-maven-plugins` does. I did not implement the `resolveCiFriendliesOnly`, but can you explain what you tried and what did not work?
Why cant you just use the regular default flatten mode?

**Comment by alexsuter** [comment]
As stated in the javadoc for `resolveCiFiendliesOnly`

> Only resolves variables revision, sha1 and changelist. Keeps everything else. 

This means for me e.g.:

+ parent pom
+ child pom

When I use `resolveCiFiendliesOnly` in my child pom, I still have the `<parent />` in my child pom, which means I still need to deploy the parent pom. I need everything, but I like to have it just flat. Don't remove anything. Maybe we can call a 'flatt-full-pom' :).

Do you understand me?

**Comment by lasselindqvist** [comment]
Hi. Can you provide an example input and output poms?
