### ISSUE TITLE
Do a release ?

### ISSUE THREAD

**Issue by gnodet** [mojohaus/flatten-maven-plugin#125]
Any idea when it would be possible to have a release of the plugin ?

**Comment by gnodet** [comment]
@hohwille ?

**Comment by lasselindqvist** [comment]
Any specific fix that you are waiting for?

**Comment by gnodet** [comment]
@lasselindqvist yes, https://github.com/mojohaus/flatten-maven-plugin/issues/96

**Comment by famod** [comment]
For me it is #89 (partial fix).

**Comment by qerub** [comment]
I'm also waiting for a release that resolves #89. So is @vinsgithub and @dreis2211. Is there anything we can do to help? I could provide a backport to 1.1 if somebody created a 1.1.x branch in Git.

**Comment by qerub** [comment]
I took things into my own hands hoping to accelerate things and prepared a 1.1.x branch at https://github.com/qerub/flatten-maven-plugin/commits/1.1.x with 1) a bump from 1.1.0 to 1.1.1-SNAPSHOT 2) a backport of #96/#97 3) the partial fix for #89 4) a maven-release-plugin:prepare run. @lasselindqvist: Feel free to just copy the branch. Or don't; I won't take offence. 😊

**Comment by lasselindqvist** [comment]
I'll have to check with @hohwille about making a release, since there is a special process for releasing Mojohaus Maven plugins, which I have not yet done.

**Comment by famod** [comment]
I appreciate @qerub's work but why not just releasing from master? 1.2.0?

**Comment by nlitterat** [comment]
For me it is #89

**Comment by qerub** [comment]
@famod: Sorry, I forgot to the state the context. @vinsgithub mentioned in #89 that a hotfix could be advisable if 1.2.0 is unreleasable (for some reason). Releasing 1.2.0 is definitively better if possible. If it isn't, I provided backported commits to save some time for the releaser.

**Comment by lasselindqvist** [comment]
The plan is to release 1.2.0 from master, and I will get it done once I have acquired the necessary rights.

**Comment by famod** [comment]
Seems 1.2.1 is now available. Thanks you, @lasselindqvist!

**Comment by lasselindqvist** [comment]
This is indeed now release and can be used with

```
<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>1.2.1</version>
</plugin>
```

Version 1.2.0 ended up skipped due to technical issues.
