### ISSUE TITLE
Flattened pom is in reverse resolution order

### ISSUE THREAD

**Issue by stephaniewang526** [mojohaus/flatten-maven-plugin#131]
We configured our plugin in parent pom as below:
```
<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>1.2.1</version>
        <executions>
          <!-- enable flattening -->
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
          <!-- ensure proper cleanup -->
          <execution>
            <id>flatten.clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <flattenDependencyMode>all</flattenDependencyMode>
        </configuration>
</plugin>
```
We observed that the flattened pom has a resolution order in reverse of the original pom. It should be in the correct order. @saturnism

**Comment by rfscholte** [comment]
You know my answer as well: my focus is fully on Apache Maven, somebody else needs to call `mvndebug`

**Comment by saturnism** [comment]
> You know my answer as well: my focus is fully on Apache Maven, somebody else needs to call `mvndebug`

yeah i know 😄 you were right abt the need to check the resolution order.

**Comment by famod** [comment]
> /cc @famod @hohwille

I'll pass that on to @lasselindqvist who released 1.2.0 and 1.2.1.

I am just a common contributor. 😉

**Comment by lasselindqvist** [comment]
I am more than happy to try to fix this if I get an example project.

**Comment by famod** [comment]
@lasselindqvist it seems @stephaniewang526 has already created a PR with a fix: https://github.com/mojohaus/flatten-maven-plugin/pull/134
