### ISSUE TITLE
Proposal: Introduce new parameter "excludeBuildPlugins" to strip out all build plugins

### ISSUE THREAD

**Issue by stephaniewang526** [mojohaus/flatten-maven-plugin#133]
**Problem**
We're trying to implement flatten-maven-plugin in https://github.com/googleapis/java-bigquerystorage and a <build> plugin with <extensions> set to `true` is brought into the flattened pom from shared-config which is undesirable. We don't want to expose this plugin to our consumers.

The flattened pom:
```
...
  <build>
    <plugins>
      <plugin>
        <groupId>org.sonatype.plugins</groupId>
        <artifactId>nexus-staging-maven-plugin</artifactId>
        <version>1.6.8</version>
        <extensions>true</extensions>
      </plugin>
    </plugins>
  </build>
...
```

The plugin config:
```
    <plugins>
      <!-- flatten maven plugin -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>1.2.1</version>
        <executions>
          <!-- enable flattening -->
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
          <!-- ensure proper cleanup -->
          <execution>
            <id>flatten.clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <flattenDependencyMode>all</flattenDependencyMode>
        </configuration>
      </plugin>
```

**Proposal**
Introduce a new parameter, `excludeBuildPlugins` in <configuration> to strip out all build plugins from the flattened pom.

Collaborator: @saturnism

**Comment by stephaniewang526** [comment]
@rfscholte Hi Robert, I see that you made a code change to fix MOJO-2038 in 2014 to include build plugins that are extensions -- you added comment `// plugins with extensions must stay`. Could you explain why this has to be the case? I searched but am unable to see the Jira issue. Thanks!

```
// plugins with extensions must stay
        Build build = effectivePom.getBuild();
        if ( build != null )
        {
            for ( Plugin plugin : build.getPlugins() )
            {
                if ( plugin.isExtensions() )
                {
                    Build cleanBuild = cleanPom.getBuild();
                    if ( cleanBuild == null )
                    {
                        cleanBuild = new Build();
                        cleanPom.setBuild( cleanBuild );
                    }
                    Plugin cleanPlugin = new Plugin();
                    cleanPlugin.setGroupId( plugin.getGroupId() );
                    cleanPlugin.setArtifactId( plugin.getArtifactId() );
                    cleanPlugin.setVersion( plugin.getVersion() );
                    cleanPlugin.setExtensions( true );
                    cleanBuild.addPlugin( cleanPlugin );
                }
            }
        }
```

**Comment by rfscholte** [comment]
Plugins can define (custom) lifecycles, their Archivers and UnArchivers. In that case you must set extension to `true`. In case of `dependency:unpack` Maven should look for those plugins to get the correct UnArchiver.
This is just one example, but plugins with extensions may contain more comparable useful information. You cannot know this up front,  so these should stay.

**Comment by stephaniewang526** [comment]
Thank you Robert. We do need this plugin as`<extensions>true</extensions>` since we're using it to override the default mvn deploy lifecycle. However, we decided that we do not need it in the flattened pom since it should not needed by the consumers of our client. 

Is there an exclusion rule or configuration settings we could use to exclude this plugin from the flattened pom?

**Comment by saturnism** [comment]
If A consume B, and B is flattened w/ the extension, will that matter? I'm thinking the scenario where this needs to be kept is if A inherits B to build.

If not needed, we can look into a PR to provide a configuration to remove.

**Comment by saturnism** [comment]
@stephaniewang526 and i discussed a few other design offline; another thought is to make this exclusion more generic, e.g., currently there is `pomElements` block for inclusions, we can also add `excludePomElements` block to exclude certain sections.

another thought - if we stick w/ a flag, then maybe it should be a flag that's specific to the behavior of whether to exclude plugin extensions.  `excludePluginExtensions`, where the default is `false` to maintain existing behavior, and can be turned to `true`

**Comment by lasselindqvist** [comment]
Maybe expand on the FlattenDescriptor https://www.mojohaus.org/flatten-maven-plugin/apidocs/org/codehaus/mojo/flatten/FlattenDescriptor.html
to make plugins configurable the same way?

**Comment by rfscholte** [comment]
My advice: don't go for a boolean. In the end you might want to control some plugins to be included. Better go for groupId:artifactId, with wildcard support. As said: there are cases where you do need the buld-plugin, because it is also an extension.

**Comment by stephaniewang526** [comment]
Thanks for your comments. Based on @lasselindqvist 's suggestion, @saturnism and I tried to configure the plugin as below and it removed the entire <build> section from the flattened pom:

```
        <configuration>
          <pomElements>
            <build>remove</build>
          </pomElements>
        </configuration>
```
As this is now resolved, we will close the issue.
