### ISSUE TITLE
Eclipse: resolving flatten-maven-plugin - No marketplace entries found

### ISSUE THREAD

**Issue by skofgar** [mojohaus/flatten-maven-plugin#146]
Hello, 

This might be more of a maven problem than related to the `flatten-maven-plugin`, but I hope you can point me in the right direction. I have a parent-pom and another project, that depends on the parent-pom. Let's call them "parent" and "child". 

Whenever I import the parent and the child into Eclipse I get the error, that it cannot find a marketplace entry for flatten-maven-plugin. Only my parent pom imports the flatten-maven-plugin. This configuration works fine when using the command-line and all commands from mvn compile to deploy or install work without any problems, it works in our CI system and it works fine with IntelliJ as well. However, when using Eclipse it it labels the `<parent>` tag as red and unless I include the `<?m2e ignore?>` (see below) - it won't work in Eclipse at all. With the ignore tags included, I get the following import warning, but as long as I refresh the project every time I modify the pom, it still seems to work:

<img width="670" alt="Screen Shot 2020-05-04 at 12 25 27" src="https://user-images.githubusercontent.com/2419749/81005508-e87ff480-8e02-11ea-8765-572bea3bc3f4.png">

Parent project, adding flatten-maven-plugin:

```
<plugin>
	<!-- Upon deployment, the flattening replaces all variables
		(e.g. revision) with actual values.-->
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>flatten-maven-plugin</artifactId>
	<version>1.2.2</version>
	<configuration>
		<updatePomFile>true</updatePomFile>
		<flattenMode>resolveCiFriendliesOnly</flattenMode>
	</configuration>
	<executions>
		<execution>
			<?m2e ignore?>
			<id>flatten</id>
			<phase>process-resources</phase>
			<goals>
				<goal>flatten</goal>
			</goals>
		</execution>
		<execution>
			<?m2e ignore?>
			<id>flatten.clean</id>
			<phase>clean</phase>
			<goals>
				<goal>clean</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

Child project referring to parent:

<img width="830" alt="Screen Shot 2020-05-04 at 12 27 25" src="https://user-images.githubusercontent.com/2419749/81005634-21b86480-8e03-11ea-8bcc-40e34a4a93cb.png">

**Comment by famod** [comment]
I'd say this plugin should be extended to contain the respective m2e-descriptor to ignore it by default.

Having said that, I wonder whether your problem is related to `relativePath` being empty.
You do release the parent individually, don't you?
