### ISSUE TITLE
Feature request: Ignore annotation processors dependencies

### ISSUE THREAD

**Issue by jorsol** [mojohaus/flatten-maven-plugin#189]
Some dependencies are just compile-only like annotation processors, using an annotation to generate code is very common, but right now is not possible to skip or ignore even with the `<scope>provided</scope>` and `<optional>true</optional>` set in the pom.

As an example of dependencies that I wish to ignore in the flattened pom are:
```xml
    <dependency>
      <groupId>org.immutables</groupId>
      <artifactId>value</artifactId>
      <version>${immutables.version}</version>
      <scope>provided</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.immutables</groupId>
      <artifactId>builder</artifactId>
      <version>${immutables.version}</version>
      <scope>provided</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <!-- Not an annotation processor, but would be ok to skip too -->
      <groupId>org.eclipse.jdt</groupId>
      <artifactId>org.eclipse.jdt.annotation</artifactId> 
      <version>${eclipse-annotation.version}</version>
      <scope>provided</scope>
      <optional>true</optional>
    </dependency>
```

So having a feature to skip some dependencies would be great.

**Comment by hohwille** [comment]
So you are suggesting to filter out dependencies that have `scope` set to `provided` and/or `optional` set to `true`?
IMHO such dependencies are just some kind of "documentation" for consumer POM view. Therefore this is IMHO not what typically users of flatten plugin want to have.
So what would be the purpose of such feature? Save some bytes in the size of the flattened POM?
Do net get me wrong: I still see it a reasonable feature to have a config option for this but IMHO priority is very low and my activity here is quite limited to build such PR myself... However, PR fixing this would be welcome.

**Comment by lasselindqvist** [comment]
https://github.com/mojohaus/flatten-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java#L1190
contains relevant code. It currently seems to filter out only test-scoped dependencies. IT could filter out provided-scoped as well, perhaps if some parameter is given (or if no downsides, always. I am not sure if there would be downsides/problems)

**Comment by jorsol** [comment]
It looks like this https://github.com/mojohaus/flatten-maven-plugin/blob/05950cbe256486cbd37ddf1511ba10d8e3e31aa6/src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java#L1093-L1096 already does the trick, so essentially you need to set `optional=true` and `flattenDependencyMode=all`.
