### ISSUE TITLE
Windows builds fails in CI

### ISSUE THREAD

**Issue by lasselindqvist** [mojohaus/flatten-maven-plugin#191]
All Windows builds fail. See for example for JDK 8:
https://github.com/mojohaus/flatten-maven-plugin/runs/1681994488?check_suite_focus=true

```
 -------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.codehaus.mojo.flatten.CreateEffectivePomTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.261 sec - in org.codehaus.mojo.flatten.CreateEffectivePomTest
Running org.codehaus.mojo.flatten.FlattenMojoTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.047 sec <<< FAILURE! - in org.codehaus.mojo.flatten.FlattenMojoTest
keepsProfileActivationFile(org.codehaus.mojo.flatten.FlattenMojoTest)  Time elapsed: 1.047 sec  <<< ERROR!
java.io.IOException: Can't delete %ssrc\test\resources\resolve-properties-ci-do-not-interpolate-profile-activation-file\.flattened-pom.xml
	at org.codehaus.mojo.flatten.FlattenMojoTest.removeFlattenedPom(FlattenMojoTest.java:86)
```

The error message looks weird with the "%s" but that seems to be due to the faulty message creation in https://github.com/mojohaus/flatten-maven-plugin/blob/80dadfd6b62ce3798725374fe95a716caf1f8cf5/src/test/java/org/codehaus/mojo/flatten/FlattenMojoTest.java#L86

There are plenty of unclosed streams (https://github.com/mojohaus/flatten-maven-plugin/blob/80dadfd6b62ce3798725374fe95a716caf1f8cf5/src/test/java/org/codehaus/mojo/flatten/FlattenMojoTest.java#L73) not sure if they cause this on Windows, or if it is something else.

**Comment by famod** [comment]
@lasselindqvist your analysis was spot on! #193 should fix it.

**Comment by dehasi** [comment]
@lasselindqvist @famod that you for quick reaction and fixing it. I planned to take a look at it this weekend.
It was my change that led to this fail. :(

**Comment by famod** [comment]
@dehasi no worries, took me less then 10 minutes.
