### ISSUE TITLE
The flatten goal change the URLs and scm connection

### ISSUE THREAD

**Issue by jorsol** [mojohaus/flatten-maven-plugin#197]
The flatten goal updates the URLs from the pom.xml, but it creates wrong links for multi-module projects.

Example parent pom (correct information):
```xml
...
  <modelVersion>4.0.0</modelVersion>
...
  <url>https://gitlab.com/demogroup/demoproject</url>
...
  <scm>
    <connection>scm:git:git@gitlab.com:demogroup/demoproject.git</connection>
    <developerConnection>scm:git:git@gitlab.com:demogroup/demoproject.git</developerConnection>
    <url>https://gitlab.com/demogroup/demoproject</url>
  </scm>

  <modules>
    <module>demomodule</module>
    ...
  </modules>
...
```

When the module `demomodule` is flattened it generate this pom.xml:
```xml
...
  <modelVersion>4.0.0</modelVersion>
...
  <url>https://gitlab.com/demogroup/demoproject/demomodule</url>
...
  <scm>
    <connection>scm:git:git@gitlab.com:demogroup/demoproject.git/demomodule</connection>
    <developerConnection>scm:git:git@gitlab.com:demogroup/demoproject.git/demomodule</developerConnection>
    <url>https://gitlab.com/demogroup/demoproject/demomodule</url>
  </scm>
...
```

Note that the flattened pom of the `demomodule` (and all other modules) the URLs are changed and appended with the path of the `demomodule`, BUT this is wrong as an invalid link is generated, GitLab, for instance, return a 404 for that link.

The expected behavior is to preserve the same URL in the modules (unless is explicitly overridden).

**Comment by lasselindqvist** [comment]
What configuration are you using to reproduce this? Just flatten and no other configs?

**Comment by jorsol** [comment]
> What configuration are you using to reproduce this? Just flatten and no other configs?

`<flattenMode>ossrh</flattenMode>`

```xml
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>flatten-maven-plugin</artifactId>
          <version>${flatten-maven-plugin.version}</version>
          <executions>
            <execution>
              <id>flatten</id>
              <phase>process-resources</phase>
              <goals>
                <goal>flatten</goal>
              </goals>
            </execution>
            <execution>
              <id>flatten-clean</id>
              <phase>clean</phase>
              <goals>
                <goal>clean</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <flattenMode>ossrh</flattenMode>
          </configuration>
        </plugin>
```

**Comment by lasselindqvist** [comment]
https://github.com/mojohaus/flatten-maven-plugin/blob/b57c50783292cf1da4c27b70a7640bb73844087d/src/main/java/org/codehaus/mojo/flatten/FlattenMode.java#L110

uses expand for URL and others, which causes this I guess. There is a reason for this dynamic creation of sub-URLs, but I don't know the origin of it.

https://github.com/mojohaus/flatten-maven-plugin/blob/master/src/it/projects/optional-elements-pomElements-suggested/pom.xml#L55
shows by example how you could configure this plugin to handle each block the way you want. In your case, maybe "resolve" for url and scm is what you would want.

**Comment by jorsol** [comment]
I have done some quick tests with `ElementHandling`, none of them works for my use case.

I just noted that the `ossrh` config just take the element from the effective POM, so this is not actually a problem in flatten-maven-plugin, but in how Maven generates the effective pom... from the docs:

> Element : url
> 3.0.0+
> The URL to the project's homepage. 
> Default value is: parent value [+ path adjustment] + (artifactId or project.directory property), or just 
>  parent value if project's child.project.url.inherit.append.path="false"
> 
> Data Type : string

The attribute since Maven 3.6.1:
* https://maven.apache.org/ref/3.6.3/maven-model/maven.html#project

So the solution is basically to use `child.project.url.inherit.append.path=false` in the `<project>` and `child.scm.connection.inherit.append.path="false" child.scm.developerConnection.inherit.append.path="false" child.scm.url.inherit.append.path="false"` in the `<scm>`.

The flattened pom keeps the attributes from `<scm>` but that is a minor issue, so closing this, Thanks!

**Comment by sbernard31** [comment]
I faced same kind of issue. 
Using :
```xml
    <scm
        child.scm.developerConnection.inherit.append.path="false"
        child.scm.url.inherit.append.path="false">
```
solves the issue but as @jorsol  says : 

> The flattened pom keeps the attributes from <scm>.

I agree this is probably a minor issue but this is not so elegant.

Any way to remove it ? (by configuration or as new feature/bug fix)

**Comment by pzygielo** [comment]
> > The flattened pom keeps the attributes from .
> 
> I agree this is probably a minor issue but this is not so elegant.

Coming here for the same reason. I don't like current result either. 😞 

Especially that `project/@child.project.url.inherit.append.path` is not present in flatten pom (and the `project/url` is correctly not expanded). But for `project/scm` - the attribute is present.
