### ISSUE TITLE
Release 1.2.6

### ISSUE THREAD

**Issue by lasselindqvist** [mojohaus/flatten-maven-plugin#199]
Release 1.2.6

Currently it would include:
Bump assertj-core from 3.16.1 to 3.18.1
(#57) Prevent interpolation of an activation file
(#191) Fix FlattenMojoTest on Windows
(#146) fix: Add lifecycle mapping metadata for M2E (Eclipse)

https://github.com/mojohaus/flatten-maven-plugin/compare/flatten-maven-plugin-1.2.5...master

**Comment by mtamme** [comment]
Hi!

Is there already a release date for v1.2.6? I am waiting for the profile activation fix.

Thanks
Martin

**Comment by lasselindqvist** [comment]
Mojohaus releases go through a vote and minimum 3 day voting period, but I will try to draft a vote this week with these contents. (See also mailing list https://groups.google.com/g/mojohaus-dev)

**Comment by lasselindqvist** [comment]
Released with version number 1.2.7. Closing this issue
