### ISSUE TITLE
Release notes not found for latest versions

### ISSUE THREAD

**Issue by AB-xdev** [mojohaus/flatten-maven-plugin#208]
I wasn't able to find the latest release notes for 1.2.7 / 1.2.6 on the [github releases page](https://github.com/mojohaus/flatten-maven-plugin/releases) and also not [on the website](https://www.mojohaus.org/flatten-maven-plugin/).
There is also no release notes file in the repo.

Are the releasenotes lost/missing or did i miss something?

**Comment by okorz001** [comment]
You can view commit log here:  https://github.com/mojohaus/flatten-maven-plugin/compare/flatten-maven-plugin-1.2.2...flatten-maven-plugin-1.2.7

Looks like the site hasn't been published since the build was moved to GitHub Actions.

**Comment by slawekjaranowski** [comment]
I have refreshed some of historical released page on GitHub
Documentation page will be refreshed with next release.
