### ISSUE TITLE
Vulnerability in commons-io dependency

### ISSUE THREAD

**Issue by MarcoDuran13** [mojohaus/flatten-maven-plugin#268]
Hello. 
We want to report a case with the commons-io:2.4 dependency. This dependency has been reported with some vulnerabilities and this is currently causing us problems when using the latest version (1.2.7) of flatten-maven. Please check this out and update your version of flatten-maven. Thank you!!

Screen of vulnerability reported on maven portal:
![image](https://user-images.githubusercontent.com/38987578/162260733-81dccc94-99c4-4f2d-a1f3-95e865b536ca.png)

Available versions for commons-io:
![image](https://user-images.githubusercontent.com/38987578/162261066-93ca3551-2226-4aa1-bcd8-0c7d0167dc55.png)

Doc about comons-io dependency:
![image](https://user-images.githubusercontent.com/38987578/162260892-56ea8673-8d84-43e2-97e5-386055cab153.png)

**Comment by slachiewicz** [comment]
Feel free to propose fix with pull request
