### ISSUE TITLE
Confusion about latest released version

### ISSUE THREAD

**Issue by inkarkat** [mojohaus/flatten-maven-plugin#277]
On the [MojoHaus plugin page](https://www.mojohaus.org/flatten-maven-plugin/), it lists _Version: 1.2.2 | Last Published: 2020-03-31_:

![Screenshot from 2022-05-19 10-53-27](https://user-images.githubusercontent.com/181261/169254628-01b11e71-ca49-42f0-afa0-f27458db88df.png)

Here in GitHub, _1.2.5 from 12-Aug-2020_ is shown as the last release:

![Screenshot from 2022-05-19 10-54-42](https://user-images.githubusercontent.com/181261/169254954-aa9cc58a-baff-44d9-a5a6-9dc98f7dfe32.png)

But I can already see [tags](https://github.com/mojohaus/flatten-maven-plugin/tags) for _1.2.6_ and _1.2.7_.

![Screenshot from 2022-05-19 10-53-45](https://user-images.githubusercontent.com/181261/169255558-2fa4d839-d929-4b16-8fc5-f76143a3fac8.png)

This is confusing for people looking for the latest release version; please ensure that the versions are kept in sync (or provide more context what a particular version represents if there indeed is a difference). Thanks!

**Comment by slachiewicz** [comment]
thx - the site now should be in a better state.
