### ISSUE TITLE
Contribution guidelines point to missing wiki page

### ISSUE THREAD

**Issue by clayreimann** [mojohaus/flatten-maven-plugin#280]
The [contribution gudelines](https://github.com/mojohaus/flatten-maven-plugin/blob/master/CONTRIBUTING.md?plain=1#L5) point to the wiki. Which has either been disabled, or was never enabled in the first place. If this content exists in the wiki, it would be helpful if an admin can retrieve it.

**Comment by slawekjaranowski** [comment]
For reference: https://github.com/mojohaus/mojohaus.github.io/issues/64
