### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by josple** [mojohaus/flatten-maven-plugin#292]
Release 1.3.0

Currently it would include:
- #288
- A number of library upgrades

https://github.com/mojohaus/flatten-maven-plugin/compare/flatten-maven-plugin-1.2.7...master

**Comment by josple** [comment]
I understand the [convention for releasing](https://github.com/mojohaus/flatten-maven-plugin/issues/199#issuecomment-784294936) is:
>Mojohaus releases go through a vote and minimum 3 day voting period... (See also mailing list https://groups.google.com/g/mojohaus-dev)

**Comment by josple** [comment]
As a non-contributor though I am not sure what the etiquette is in terms of me starting a VOTE 'conversation'?! Particularly as I don't believe I have the authority to perform the release.

**Comment by slawekjaranowski** [comment]
Voting is currently optional
https://www.mojohaus.org/development/performing-a-release.html

**Comment by slawekjaranowski** [comment]
You can vote here for release ... by adding reaction on this issue.
I'm interesting how many people watching project and issues :-)

**Comment by slawekjaranowski** [comment]
I will release new version in a few days.

**Comment by tiagobento** [comment]
@slawekjaranowski Hey! Just found this issue after really needing the fix for `shade-maven-plugin` compatibility (#100 ). I just tested 1.3.0-SNAPSHOT by building `master`, and it worked like a charm :)

My team would really benefit from the 1.3.0 release, so +1000 from me 👍

**Comment by slawekjaranowski** [comment]
Done.
 - new version is available
 - documentation site updated
