### ISSUE TITLE
Variable substitution during install phase does not consider environment variable

### ISSUE THREAD

**Issue by wykapedia** [mojohaus/flatten-maven-plugin#3]
Consider the command: `mvn clean flatten:flatten install -Dbuild.version=1.0.0-RELEASE`

The parent pom.xml file has a section with dynamic version based on environment variable:
```xml
    <version>${build.version}</version>
    <properties>
       <build.version>0.1-SNAPSHOT</build.version>
    </properties>
```
When running flatten, the `${build.version}` is not replaced with the environment variable, but instead replaced with the value of the fallback property `<build.version>` declared in the parent pom.  The versions of the child poms now show `<version>0.1-SNAPSHOT</version>`

**Comment by hohwille** [comment]
Thanks for the feedback. Seems to be indeed a bug. We are using a way to reuse code from maven to resolve dependencies and variables that seems to be buggy. I also found a different more complex bug related to this. I have to talk with robert scholte who implemented this approach. Maybe we have to find a completely new approach to solve the bug(s).

**Comment by hohwille** [comment]
Added integration test after some little fight with invoker plugin to let me supply command line property for IT. Now test works as expected and breaks the current build until the bug is fixed.
As you can see in ```target/it/cmd-property-substituion/build.log``` the project name is propertly resolved:
> [INFO] Building MagicValue42 0.0.1-SNAPSHOT

while the test fails with:
> [INFO]   The post-build script did not succeed. assert 'MagicValue42' == flatten
dProject.name.text()
                      |  |               |    |
                      |  |               |    FallbackDefaultValue
                      |  |               FallbackDefaultValue
                      |  4.0.0org.codehaus.mojo.flatten.itscmd-property-substitu
tion0.0.1-SNAPSHOTFallbackDefaultValue
                      false

**Comment by hohwille** [comment]
https://github.com/mojohaus/flatten-maven-plugin/blob/master/src/it/projects/cmd-property-substituion/pom.xml

**Comment by hohwille** [comment]
I added a JUnit as well so I can debug easily into mavens internals.
The problems is in ```StringSearchModelInterpolator``` or more precisely in its ```StringSearchInterpolator```. It has a list of ```valueSources```. When I debug my test this list has 8 elements. Three of them (4,5,6) are ```MapBasedValueSource```. Number 4 is empty, number 5 seems to contain the properties from the POM and number 6 contains the system properties.
As properties re interpolated and resolved in the order of these value sources the POM property is overriding the system property. So in other words the order of 5 and 6 is reversed and incorrect.
I have no clue why and how to resolve this. Parts of this code seem to have some history....

**Comment by hohwille** [comment]
```AbstractStringBasedModelInterpolator.createValueSources``` seems to be the key.
This is all done on purpose and the order is hardcoded there. So I assume that if maven is running regularly then the system properties specified on the command line are in the value source number 4 that contain ```config.getUserProperties()```.
Still I a little puzzled why ```mvn -Dproperty=foo``` allows to override the property from the POM as ```-D``` is doing nothing but setting system properties. But it seems I got very close to the fix now.

**Comment by hohwille** [comment]
```DefaultArtifactDescriptorReader``` does this:
```
modelRequest.setUserProperties( toProperties( session.getUserProperties() ) );
```

**Comment by hohwille** [comment]
So now I could easily solve the problem if I can access the user properties. I tried to inject ```LegacySupport``` as component to the mojo. The ```LegacySupport``` gives me access to the session and from there I could get the user properties. However, fun just starts:
```
Caused by: java.lang.NoSuchMethodError: org.apache.maven.plugin.LegacySupport.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;
```

**Comment by hohwille** [comment]
Problem solved via ```LegacySupport.getSession().getUserProperties()```.

**Comment by hohwille** [comment]
Travis is green now. All tests pass. Problem solved.

**Comment by hohwille** [comment]
Release is prepared. You are welcome to test and vote:
https://groups.google.com/forum/#!topic/mojohaus-dev/kHVNoyGvK5o
