### ISSUE TITLE
Allow version ranges in parent

### ISSUE THREAD

**Issue by cboehme** [mojohaus/flatten-maven-plugin#36]
Maven 3.5.0 introduces the ability to use version ranges when inheriting from a parent pom (see [MNG-2199](https://issues.apache.org/jira/browse/MNG-2199)). The flatten-maven-plugin fails to flatten poms which use this feature.

**Comment by cboehme** [comment]
Created an integration test for the issue. It can be found in the [resolve-parent-with-version-range] branch of my fork (https://github.com/cboehme/flatten-maven-plugin/tree/resolve-parent-with-version-range).

**Comment by khmarbaise** [comment]
Can you make a pull request based on your improvements?

**Comment by cboehme** [comment]
Of course, but it is only an integration test without a working implementation. I tried to resolve the version range using the implementation of `org.eclipse.aether.impl.VersionRangeResolver` injected by Maven. However, this implementation seems to rely on the remote repositories being listed in the `VersionRangeRequest` and does not work with only the local repository.

Do you want me to add may attempted solution to the pull request or should it only contain the integration test?

**Comment by khmarbaise** [comment]
The first step is having a test which proves it does not work as expected. The second step to implement a solution. But of course if have an idea for a solution please add it as well to the PR..

I have not yet dived very deep into flatten-maven-plugin code...but it might help to use the [maven-artifact-transfer shared component](http://maven.apache.org/shared/maven-artifact-transfer/index.html) (It might be that we need to improve the component). The point is `org.eclipse.aether...` is something specific to particular Maven versions which should be go away with maven-artifact-transfer component...We are using it in different maven plugins already...(but it's  far from complete but already usable)...

**Comment by cboehme** [comment]
Thanks for pointing me at the maven-artifact-transfer component. That did the trick. I updated pull request #38 accordingly.

**Comment by hohwille** [comment]
As PR #38 was already merged, this can IMHO be closed.
