### ISSUE TITLE
Composite ${revision} variable in multi-module project fails for dependency

### ISSUE THREAD

**Issue by barrypitman** [mojohaus/flatten-maven-plugin#40]
I have attached a simple maven project which illustrates my issue. 

I am defining my project version like this: `<version>${revision}</version>` as suggested here: https://maven.apache.org/maven-ci-friendly.html. 

However, my revision property itself is setup like this:
```
<properties>
    <revision>${build.number}-${branch.name}</revision>
</properties>
```
and I configure defaults for those two variables (`build.number` and `branch.name`) via profiles:
```
<profiles>
        <profile>
            <id>local</id>
            <activation>
                <property>
                    <name>!build.number</name>
                </property>
            </activation>
            <properties>
                <build.number>1</build.number>
            </properties>
        </profile>

        <profile>
            <id>defaultBranch</id>
            <activation>
                <property>
                    <name>!branch.name</name>
                </property>
            </activation>
            <properties>
                <branch.name>DEFAULT</branch.name>
            </properties>
        </profile>
    </profiles>
```

I have a parent and two child modules, artifactA and artifactB, where artifactB depends on artifactA. I declare the dependency like this in artifactB/pom.xml:
```
<dependency>
    <groupId>test</groupId>
    <artifactId>artifactA</artifactId>
    <version>${revision}</version>
</dependency>
```

When I try `mvn clean install` on the parent, I run into this error:

> [ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.0.0:flatten (flatten) on project artifactB: 1 problem was encountered while building the effective model for test:artifactB:${build.number}-${branch.name}
[ERROR] [ERROR] 'dependencies.dependency.version' for test:artifactA:jar must be a valid version but is '${build.number}-${branch.name}'. @

It seems like `${revision}` is being resolved to `${build.number}-${branch.name}`, but those two variables are not being resolved thereafter. 

This, however, works:
`mvn clean install -Dbuild.number=1 -Dbranch.name=DEFAULTX` 
Which makes me think that the flatten plugin isn't picking up the variables declared via profiles in the parent POM when resolving dependency versions?

[multi_module_dependencies.zip](https://github.com/mojohaus/flatten-maven-plugin/files/915761/multi_module_dependencies.zip)

**Comment by khmarbaise** [comment]
Why not using `${sha1}` and/or `${changelist}` instead of introducing new property..?

**Comment by barrypitman** [comment]
According to https://maven.apache.org/maven-ci-friendly.htmlm `revision` is the same as `sha1` and `changelist` - its one of three options - not a new property.

I'm building the revision property up like this: 
```
<properties>
    <revision>${build.number}-${branch.name}</revision>
</properties>
``` 
because I've always done it like that & have many projects using this approach. Of course I could simplify it but I filed the issue because I was surprised it didn't work as-is.

**Comment by khmarbaise** [comment]
No it is not one of three options they can be used together...may be I need to improve the ci firendly documentation....

**Comment by jpasquers** [comment]
Was there ever any followup to this? We have the exact same problem, and using variables inside of our revision had always worked, until we placed them in profiles in the parent POM file. It seems very reasonable to want to use a revision that has properties defined in it. We have 20+ projects, and each explicitly declaring a revision is silly.

**Comment by khmarbaise** [comment]
@jpasquers Can you please open a new issue and it would be helpful having a full test project which shows how you are using the feature...and describe/show log output what does not work...

**Comment by jameslittle** [comment]
I am seeing the same issue as this, where we are using properties within profiles with OS activation to set platform-specific variables like filepath, library path etc (for system scope dependencies).

**Comment by RPCMoritz** [comment]
Would love to see this issue reopened.
The OP's usage was a bit weird, but say, I want to resolve the local user name as a default value for `sha1` - then flatten still fails, because variable resolution is shallow/in the wrong order.
