### ISSUE TITLE
License header shouldn't be auto added

### ISSUE THREAD

**Issue by mariuszs** [mojohaus/flatten-maven-plugin#46]
I'm not sure why in my internal project after flatting Apache license is added, this is confusing because source pom.xml does not contains any license defined.

```
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>

````

**Comment by khmarbaise** [comment]
Does a  parent define something like that?

**Comment by mariuszs** [comment]
Oh, you are right. My parent contains such information `spring-boot-dependencies`, but my project has different license.... Thank you for help!

**Comment by khmarbaise** [comment]
Great that i could help. You're welcome.
