### ISSUE TITLE
Changing output directory breaks relative paths in pom file

### ISSUE THREAD

**Issue by hbakkum** [mojohaus/flatten-maven-plugin#50]
Hi there,

Just a note on changing the output directory for the generated pom file:

I changed this to the /target directory and then noticed some of my tests were no longer being run. After some digging the reason for this was that when this plugin updates the pom file with the flattened version it uses MavenProject:setFile(File). However the pom File's parent directory can be used for resolving relative paths in other plugins, in my case this was the build-helper-maven-plugin, so any relative paths used in this plugin were now relative to my /target directory not the modules base directory and this caused issues trying to add additional test source directories. What made this trickier to track down was the fact that it only broke relative paths that were used in plugins that ran _after_ the flatten plugin had fired. 

So thought I'd just suggest a warning in the documentation and potentially logging a warning from the plugin too when the output directory for the generated pom file is changed from its default location.

Cheers,
Hayden

**Comment by khmarbaise** [comment]
Good catch...and yes adding a warning etc. is a really good idea..

**Comment by hbakkum** [comment]
Actually, looking forward, it looks like since maven 3.2.5 a new method exists to update the pom without changing the basedir: http://maven.apache.org/ref/3.2.5/apidocs/org/apache/maven/project/MavenProject.html#setPomFile(java.io.File)

**Comment by jglick** [comment]
…which is already in use. See #30 then #53.

**Comment by hohwille** [comment]
As #30 has been merged, I consider this done.
