### ISSUE TITLE
Version configuration is missing

### ISSUE THREAD

**Issue by cemo** [mojohaus/flatten-maven-plugin#6]
I am using a hack to create some artifacts. Everything is working nice but flatten plugin is evaluating `maven.build.timestamp` again before fixing version. This is pretty bad because the version inside pom and name of the artifact is not same and this is causing an error on my side. Is there any workaround for this issue?

```xml
   <version>${timestamp}</version>

   <properties>  
       <maven.build.timestamp.format>YYMMddHHmmss</maven.build.timestamp.format>
      <timestamp>${maven.build.timestamp}</timestamp>
   </properties>
```

Edit: I have fiddle with this plugin and noticed that version is missing in FlattenDescriptor.

**Comment by hohwille** [comment]
PR #8 has been merged. I will close this as fixed. Let me know if you test SNAPSHOT and something is still wrong.
