### ISSUE TITLE
Add feature to rewrite artifactId in flattened pom.

### ISSUE THREAD

**Issue by tribbloid** [mojohaus/flatten-maven-plugin#61]
This patch intend to allow user to cross-build one project into multiple maven artifacts, each with a different artifactId.

The requirement to build into multiple artifacts from a single codebase is pervasive, particularly for Scala projects that have to be compiled for different Scala binary versions, e.g. [Apache Spark Core 2.2.0](https://mvnrepository.com/artifact/org.apache.spark/spark-core) should be built into the following 2 artifacts:

org.apache.spark:spark-core_2.11:jar:2.2.0
org.apache.spark:spark-core_2.10:jar:2.2.0

Comparing to sbt, all existing maven plugins have very limited support for this requirement. (See [this post](http://www.hammerlab.org/2017/04/06/scala-build-tools/#regexing-poms)  for detail). Most makeshift solutions required modifying codebase, or creating an ill-formed pom file.

With this patch, such cross-building can be achieved with a single configuration option:

```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
       ....
        <configuration>
          <artifactIdOverride>${project.artifactId}_${scala.binary}</artifactIdOverride>
        </configuration>
      </plugin>
```

For this project and each of its submodules, the above configuration will generate a flatten-pom.xml with its artifactId rewritten based on provided ${scala.binary} maven property/profile.

As far as I know this is the only method for scala cross-building that doesn't require codebase change or declaring multiple submodules.

Will send a pull request shortly, any advice?

**Comment by hohwille** [comment]
This issue seems to be some kind of missunderstanding.
* "This patch..." is confusing. It is actually talking about #62 
* As commented in #62 you should simply set the `artifactId` to a variable that can then be overriden.
* Further if you are talking about cross-build (multiple plattforms like linux, windows, mac) you should consider classifiers instead.

Hence I am closing this issue.
