### ISSUE TITLE
handling of <version>${revision}</version>

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [mojohaus/flatten-maven-plugin#63]
in the continuous release scenario:
* https://maven.apache.org/maven-ci-friendly.html

when using `<version>${revision}</version>` based on `${maven.build.timestamp}`

`flatten` will produce different version from the actual artifact

because flatten model builder will evaluate `${maven.build.timestamp}` 
again, separately form maven core evaluation

perhaps plugin needs a re-design:
* use only maven core model
* then produce reduced model by filtering
* rather then building separate maven model from scratch

**Comment by hohwille** [comment]
Resolved with PR #77
