### ISSUE TITLE
<name> metadata not added to generated child pom files

### ISSUE THREAD

**Issue by bbarker** [mojohaus/flatten-maven-plugin#76]
The output pom files generated by the flatten-maven-plugin(v 1.0.1) contains all the metadata elements I need to publish on OSSRH when `<flattenMode>ossrh</flattenMode>` is specified, or when individual fields are specified with `<pomElements>`. However, the flattened child poms in my project are missing one element required by OSSRH: the project `<name>`. The flattened parent pom does contain `<name>`.

My original issue is described [here](https://stackoverflow.com/questions/52173260/how-to-resolve-parent-pom-dependency-issue-failed-to-read-artifact-descriptor), the solution worked after some tweaks; the final workaround is described in a [comment](https://stackoverflow.com/questions/52173260/how-to-resolve-parent-pom-dependency-issue-failed-to-read-artifact-descriptor#comment91464209_52173650), but I'm wondering if this workaround is actually necessary (or, maybe it is even a bug, since it seems unlikely all the other metadata elements would be copied over without issue).

Cross referencing with the SO question: https://stackoverflow.com/questions/52263261/why-isnt-name-metadata-added-to-child-pom-files-generated-by-the-flatten-mave

**Comment by lasselindqvist** [comment]
I think the real issue here is that the name element is not inherited by child poms.
https://maven.apache.org/pom.html#Inheritance says:
> Notable elements which are not inherited include:
> 
>     artifactId
>     name
>     prerequisites

Inheritance is why it is enough to add <url>someurl</url> to the parent and get <url>someurl/child</url> in the flattened child poms.

So, the flattened child poms will contain the name only if it is added to the original child poms.

**Comment by hohwille** [comment]
IMHO we can not create elements that are not there. `<name>` is designed to be the individual name of the maven module. It is not required and falls back to artifactId via maven defaults if not present. We can not make up something better with magic.
