### ISSUE TITLE
Create release 1.1.0

### ISSUE THREAD

**Issue by hohwille** [mojohaus/flatten-maven-plugin#82]
push out release to maven central.

**Comment by hohwille** [comment]
Vote is running:
https://groups.google.com/forum/#!topic/mojohaus-dev/u28wlFOuSrU

If passed OK only releasing in OSSRH and done.

**Comment by bric3** [comment]
I think this issue can be closed, as 1.1.0 is already available.

**Comment by hohwille** [comment]
https://repo1.maven.org/maven2/org/codehaus/mojo/flatten-maven-plugin/1.1.0/
