### ISSUE TITLE
When using Maven 3.6, a pom that imports a bom in its dependency management from a repository other than Maven Central cannot be flattened

### ISSUE THREAD

**Issue by wilkinsona** [mojohaus/flatten-maven-plugin#89]
I've encountered a problem with 1.1.0 of the Flatten Maven Plugin when used with Maven 3.6.0 in Spring Boot's build. I've boiled things down to a much simpler example which is available in [this GitHub repository](https://github.com/wilkinsona/flatten-maven-plugin-problem). The README hopefully does a reasonable job of explaining the problem. In a nutshell, when using Maven 3.5.4 the repository configured in the root pom is available to resolve the imported bom and flattening works. When using Maven 3.6.0, the repository configured in the root pom is not available to resolve the imported bom and flattening fails.

Some [initial analysis](https://github.com/spring-projects/spring-boot/issues/16167) would suggest that our use of `${revision}` is important to the problem. If I replace it with a hardcoded version the problem then occurs with both 3.5.4 and 3.6.0. This makes me suspect that either I'm doing something wrong, or there's a bug in the Flatten Maven Plugin. My apologies for opening an issue if it's the former, but a pointer to the correct approach would be much appreciated. If it's the latter, please let me know if there's anything I can do to help to diagnose the problem.

**Comment by famod** [comment]
Same here, different BOM:
```
15:47:14  [ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.1.0:flatten (flatten) on project root: 1 problem was encountered while building the effective model for com.somecompany.someproject:root:1.4.0-SNAPSHOT
15:47:14  [ERROR] [FATAL] Non-resolvable parent POM for org.jboss.bom.eap:jboss-javaee-6.0-with-hibernate:6.4.21.GA: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.jboss.bom.eap:jboss-eap-bom-parent:pom:6.4.21.GA @ org.jboss.bom.eap:jboss-javaee-6.0-with-hibernate:6.4.21.GA
```
Maven version is 3.6.1.

A less than ideal workaround for my special (corporate) setup is using a mirror in `settings.xml`. That mirror needs to know/contain the respective BOMs.

**Comment by famod** [comment]
After countless debugging sessions, I was able to isolate the problem:
[../blob/master/src/main/java/org/codehaus/mojo/flatten/model/resolution/FlattenModelResolver.java](FlattenModelResolver) was obviously never meant to perform dependency resolutions, given methods like:
```java
    public void addRepository( Repository repository, boolean replace )
    {
        // ignoring... artifact resolution via repository should already have happened before by maven core.
    }
```
But unfortunately, that changed in [this commit ("Handle parent poms with version ranges correctly")](https://github.com/mojohaus/flatten-maven-plugin/commit/d7ff0fab9d87aae18ff32e3fa094878a08afbed9#diff-68ff93687822060c33569273ab6479d7R151).

AFAICT, custom repositories are added by Maven Core via `ModelResolver.addRepository()`. Since both methods are empty in `FlattenModelResolver`, the `projectBuildingRequest` that is passed to `depencencyResolver.resolveDependencies()` will never contain those custom repositories and the resolution will be performed solely against `central`.

I am going to submit a PR that fixes this bug for the non-version-ranged case. A clean fix for all cases will be much harder to implement and has to be discussed first.
There is also a settings profile handling problem...

**Comment by famod** [comment]
Might be related: #69

**Comment by famod** [comment]
@wilkinsona PR #98 should fix your case (it does fix mine). I'd very much appreciate it if you could give it shot - thanks!

**Comment by hasanunlukilinc** [comment]
> @wilkinsona PR #98 should fix your case (it does fix mine). I'd very much appreciate it if you could give it shot - thanks!
> 
> **Edit**: Just tried it with https://github.com/wilkinsona/flatten-maven-plugin-problem **and it does fix the problem!**.

I have a smilar case, even I defined "revision" as a  property  in the top pom.xml and I also write relativePath in child pom.xml   when I try to   run  for child project  
`-Drevision=1.1.1 clean install spring-boot:repackage `  

I saw 

`[INFO] Downloading from archiva.internal: http://localhost:8080/repository/internal/io/geniusbrain/$%7Brevision%7D/geniusbrain-$%7Brevision%7D.pom
`

It can not understand revisionNumber

**Comment by fprochazka** [comment]
I've encountered the same problem. We have bunch of external repos configured as remotes in our Artifactory instance, and when I run the flatten configuration I get an error, that artifact cannot be resolved, because it's not on central.

```
[DEBUG] Verifying availability of /home/fprochazka/.m2/repository/org/springframework/cloud/spring-cloud-dependencies-parent/2.1.0.M2/spring-cloud-dependencies-parent-2.1.0.M2.pom from [central (https://repo.maven.apache.org/maven2, default, releases)]
[WARNING] The POM for org.springframework.cloud:spring-cloud-dependencies-parent:pom:2.1.0.M2 is missing, no dependency information available
```

```
[ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.1.0:flatten (flatten-effective-pom) on project cogvio-framework-dependencies: 2 problems were encountered while building the effective model for com.cogvio.framework:cogvio-framework-dependencies:0.0.1.BUILD-SNAPSHOT
[ERROR] [FATAL] Non-resolvable parent POM for org.springframework.cloud:spring-cloud-zookeeper-dependencies:2.1.0.M1: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find org.springframework.cloud:spring-cloud-dependencies-parent:pom:2.1.0.M2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ org.springframework.cloud:spring-cloud-zookeeper-dependencies:2.1.0.M1
[ERROR] [FATAL] Non-resolvable parent POM for org.springframework.cloud:spring-cloud-cloudfoundry-dependencies:2.1.0.M1: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find org.springframework.cloud:spring-cloud-dependencies-parent:pom:2.1.0.M2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ org.springframework.cloud:spring-cloud-cloudfoundry-dependencies:2.1.0.M1
```

**Comment by vinsgithub** [comment]
Is there any plan to to release this fix? It's a really blocking issue IMHO.
if 1.2.0 version is too far from being released, maybe a hotfix should be advisable.

Thank you.
