### ISSUE TITLE
Proposal: Completely flatten direct & transitive dependencies

### ISSUE THREAD

**Issue by saturnism** [mojohaus/flatten-maven-plugin#92]
### Problem
If a parent pom ([example](https://github.com/saturnism/dependency-conflict-examples/blob/master/example-3a-manage-all/pom.xml)) uses `dependencyManagement` to manage dependency versions, the managed versions will be applied to both direct dependencies & transitive dependencies.

E.g., the dependency tree: for the above pom has managed versions of error_prone_annotations & guava.:

```
com.example.deps.example3:module-a:jar:1.0-SNAPSHOT
+- com.google.guava:guava:jar:26.0-jre:compile
|  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
|  +- org.checkerframework:checker-qual:jar:2.5.3:compile (version managed from 2.5.2)
|  +- com.google.errorprone:error_prone_annotations:jar:2.3.1:compile (version managed from 2.1.3)
|  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
|  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
\- com.google.truth:truth:jar:0.42:compile
   +- (com.google.guava:guava:jar:26.0-jre:compile - version managed from 25.1-android; omitted for duplicate)
   +- org.checkerframework:checker-compat-qual:jar:2.5.3:compile
   +- (org.checkerframework:checker-qual:jar:2.5.3:compile - version managed from 2.5.2; omitted for duplicate)
   +- junit:junit:jar:4.12:compile
   |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
   +- com.googlecode.java-diff-utils:diffutils:jar:1.3.0:compile
   +- com.google.auto.value:auto-value-annotations:jar:1.6.2:compile
   \- (com.google.errorprone:error_prone_annotations:jar:2.3.1:compile - version managed from 2.1.3; omitted for duplicate)
```

When a consumer uses an artifact that was built this way ([example](https://github.com/saturnism/dependency-conflict-examples/blob/master/example-4-validation/validation-project/pom.xml)), the consumer will see a dependency tree that only has the direct dependency reflecting the right version (e.g., guava:26.0-jre), but not the transitive dependency versions:

```
com.example.deps.example4:validation-project:jar:1.0.0-SNAPSHOT
\- com.example.deps.example4:module-a:jar:1.0-SNAPSHOT:compile
   +- com.google.guava:guava:jar:26.0-jre:compile
   |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
   |  +- org.checkerframework:checker-qual:jar:2.5.2:compile
   |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
   |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
   |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
   \- com.google.truth:truth:jar:0.42:compile
      +- (com.google.guava:guava:jar:25.1-android:compile - omitted for conflict with 26.0-jre)
      +- org.checkerframework:checker-compat-qual:jar:2.5.3:compile
      +- (org.checkerframework:checker-qual:jar:2.5.3:compile - omitted for conflict with 2.5.2)
      +- junit:junit:jar:4.12:compile
      |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
      +- com.googlecode.java-diff-utils:diffutils:jar:1.3.0:compile
      +- com.google.auto.value:auto-value-annotations:jar:1.6.2:compile
      \- (com.google.errorprone:error_prone_annotations:jar:2.3.1:compile - omitted for conflict with 2.1.3)
```

When using current version of `flatten-maven-plugin`, it also only configures the direct dependency versions, and not the transitive dependency versions.

### Proposal
Add a new `dependencyMode` to be able to to flatten transitive dependencies as well, so that it generates a release pom that reflects all dependency versions used during the build.

In this mode, all the transitive dependencies will be pulled up as a direct dependency; to satisfy convergence enforcer rules, conflicting dependency versions are excluded.

There was a prior example of this through `release-pom` plugin (https://github.com/rvowles/release-pom). The plugin applies exclusions rules using wildcard, e.g., `<exclusions><exclusion><groupId>*</...> ... </...></...>`. While this works well for builds, dependency convergence enforcer (and specifically, parts in Maven Core) doesn't respect the wildcard exclusions.

**Comment by saturnism** [comment]
Actually, to make the transition easier, we can keep `flattenMode`, and add `dependencyMode`

**Comment by suztomo** [comment]
DependencyManagement behaves differently based on the location of a dependency tree.

When used at the root of the tree
- Specifies versions of its direct dependencies if missing
- Controls versions of transitive dependencies
  Example: [example-4-validation/module-a](https://github.com/saturnism/dependency-conflict-examples/blob/master/example-4-validation/module-a/pom.xml) does not fail dependency convergence.

When used at non-root nodes in the tree (e.g., libraries using BOM)
- Specifies versions of the node's direct dependencies if missing
  Example: [google-http-client](https://search.maven.org/artifact/com.google.http-client/google-http-client/1.29.1/jar)'s parent specifies versions
- **Does not** control the versions of node's transitive dependencies
  Example: [example4-validation/validation-project](https://github.com/saturnism/dependency-conflict-examples/tree/master/example-4-validation/validation-project/pom.xml) fails dependency convergence when omitting the parent.
This is where saturnism@'s PR #93 gives value.

**Comment by hohwille** [comment]
Done with PR #93

**Comment by saturnism** [comment]
@hohwille thnx for merging it! i noticed new version of the plugin hasn't been released, anyway to make a maven central release? thnx!
