### ISSUE TITLE
Avoid rewriting the flattened pom if nothing has changed

### ISSUE THREAD

**Issue by gnodet** [mojohaus/flatten-maven-plugin#96]
When the pom is included in the jar, this can cause the jar to be modified with each build, even if nothing has changed.

**Comment by gnodet** [comment]
@hohwille, if you have a few minutes to review and merge this PR, that would be awesome !
and eventually do a release... ;-)

**Comment by famod** [comment]
@lasselindqvist @olamy @gnodet This was merged for 1.2.0 already and should therefore be closed.
